name: Front Deployment
on:
 push:
  branches:
   - main
jobs:
 build:
  name: react build & deploy
  runs-on: ubuntu-latest
  steps:
   - name: checkout Github Action
    uses: actions/checkout@v3
   - name: Get yarn cache directory
    id: yarn-cache-dir
    run: |
     echo "::set-output name=dir::$(yarn config get cache)"
   - uses: actions/cache@v3
    id: yarn-cache
    with:
     path: ${{ steps.yarn-cache-dir.outputs.dir }}
     key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
     restore-keys: |
      ${{ runner.os }}-node-
   - name: install yarn service dir  
     working-directory: ./service
     run: yarn install --frozen-lockfile
   - name: yarn build service dir
     working-directory: ./service
     run: yarn build
   - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v1
     with:
      role-to-assume: ${{ secrets.AWS_ARN }}
      aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
   - name: Upload to S3
    env:
     BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME_A}}
    run: |
     aws s3 sync \
      ./service/build s3://$BUCKET_NAME
   - name: CloudFront Invalidation
    env:
     CLOUD_FRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID_A}}
    run: |
     aws cloudfront create-invalidation \
      --distribution-id $CLOUD_FRONT_ID --paths /*
